package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.auto.NamedCommands;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathPlannerPath;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.util.datalog.StringLogEntry;
import edu.wpi.first.wpilibj.DataLogManager;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.Constants.FuelConstants;
import frc.robot.Constants.SwerveConstants;
import frc.robot.commands.GoToPoseCommand;
import frc.robot.commands.GoToPoseFactory;
import frc.robot.commands.ResilientFollowPathCommand;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.util.ShootingOnTheFly;
import java.io.IOException;
import java.util.Optional;
import java.util.function.BooleanSupplier;
import java.util.function.Supplier;
import org.json.simple.parser.ParseException;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
@SuppressWarnings("PMD.SingularField")
public class Swerve extends TunerSwerveDrivetrain implements Subsystem {
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier;
  private double m_lastSimTime;

  private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds =
      new SwerveRequest.ApplyRobotSpeeds();

  private final SwerveRequest.FieldCentricFacingAngle m_fieldCentricFacingAngle =
      new SwerveRequest.FieldCentricFacingAngle();

  private final SwerveRequest.Idle m_idle = new SwerveRequest.Idle();

  private final StructPublisher<Pose2d> m_lookAtPointPub =
      NetworkTableInstance.getDefault()
          .getStructTopic("Drivetrain/LookAtPoint/TargetPoint", Pose2d.struct)
          .publish();

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective;

  /* Swerve requests to apply during SysId characterization */
  private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
      new SwerveRequest.SysIdSwerveTranslation();

  @SuppressWarnings("PMD.UnusedPrivateField")
  private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization =
      new SwerveRequest.SysIdSwerveSteerGains();

  private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization =
      new SwerveRequest.SysIdSwerveRotation();

  // WPILib DataLog entries for SysId state (fallback for HOOT writeString not appearing)
  private final StringLogEntry m_translationSysIdStateLog =
      new StringLogEntry(DataLogManager.getLog(), "sysid-test-state-SwerveTranslation");
  private final StringLogEntry m_rotationSysIdStateLog =
      new StringLogEntry(DataLogManager.getLog(), "sysid-test-state-SwerveRotation");

  /*
   * SysId routine for characterizing translation.
   * This is used to find PID gains for the drive motors.
   */
  private final SysIdRoutine m_sysIdRoutineTranslation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
              null, // Use default timeout (10 s)
              // Log state to both HOOT and WPILib DataLog
              state -> {
                StatusCode result =
                    SignalLogger.writeString("SysIdTranslation_State", state.toString());
                if (!result.isOK()) {
                  DataLogManager.log(
                      "SignalLogger.writeString failed for translation state: " + result);
                }
                m_translationSysIdStateLog.append(state.toString());
              }),
          new SysIdRoutine.Mechanism(
              output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

  /*
   * SysId routine for characterizing rotation.
   * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
   * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log.
   */
  @SuppressWarnings("PMD.UnusedPrivateField")
  private final SysIdRoutine m_sysIdRoutineRotation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              /* This is in radians per second^2, but SysId only supports "volts per second" */
              Volts.of(Math.PI / 6).per(Second),
              /* This is in radians per second, but SysId only supports "volts" */
              Volts.of(Math.PI),
              null, // Use default timeout (10 s)
              // Log state to both HOOT and WPILib DataLog
              state -> {
                StatusCode result =
                    SignalLogger.writeString("SysIdRotation_State", state.toString());
                if (!result.isOK()) {
                  DataLogManager.log(
                      "SignalLogger.writeString failed for rotation state: " + result);
                }
                m_rotationSysIdStateLog.append(state.toString());
              }),
          new SysIdRoutine.Mechanism(
              output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
              },
              null,
              this));

  /* The SysId routine to test */
  private final SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

  private ChassisSpeeds m_prevFieldSpeeds = new ChassisSpeeds();
  private ChassisSpeeds m_currentFieldSpeeds = new ChassisSpeeds();

  private BooleanSupplier m_shouldMirrorPath = () -> false;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public Swerve(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
    configureHeadingController();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */
  public Swerve(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
    configureHeadingController();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta] transposed, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta] transposed, with units in meters and radians
   * @param modules Constants for each specific module
   */
  public Swerve(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
    configureHeadingController();
  }

  private void configureHeadingController() {
    m_fieldCentricFacingAngle.HeadingController.setPID(
        SwerveConstants.kRotationP, SwerveConstants.kRotationI, SwerveConstants.kRotationD);
  }

  /**
   * Resets the robot pose to a known position over the bump. The base pose is defined for the blue
   * alliance near side. It is automatically mirrored for red alliance, and optionally mirrored
   * horizontally (across the field centerline) for the far side based on the supplier.
   *
   * @param mirrorHorizontally supplier that returns true to mirror the Y coordinate.
   * @return Command that resets the pose.
   */
  public Command resetRobotPoseOverBump(BooleanSupplier mirrorHorizontally) {
    return this.runOnce(
        () -> {
          Pose2d bluePose =
              new Pose2d(5.850689888000488, 2.484062433242798, new Rotation2d(0.5890486225480862));

          if (mirrorHorizontally.getAsBoolean()) {
            bluePose =
                new Pose2d(
                    bluePose.getX(),
                    Constants.FieldSpots.kFieldWidth - bluePose.getY(),
                    bluePose.getRotation().unaryMinus());
          }

          if (!Constants.ifOnBlue()) {
            bluePose = com.pathplanner.lib.util.FlippingUtil.flipFieldPose(bluePose);
          }

          resetPose(bluePose);
        });
  }

  /**
   * Sets the supplier that determines whether paths should be mirrored horizontally (left/right).
   * This must be called before auto commands are built (i.e., before the auto chooser is created).
   *
   * @param shouldMirror supplier returning true to mirror paths across the field centerline.
   */
  public void setShouldMirrorPath(BooleanSupplier shouldMirror) {
    m_shouldMirrorPath = shouldMirror;
  }

  private void configureAutoBuilder() {
    try {
      var config = RobotConfig.fromGUISettings();
      BooleanSupplier shouldFlip =
          () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red;

      AutoBuilder.configureCustom(
          (PathPlannerPath path) ->
              Commands.defer(
                  () -> {
                    PathPlannerPath pathToFollow =
                        m_shouldMirrorPath.getAsBoolean() ? path.mirrorPath() : path;
                    return new ResilientFollowPathCommand(
                        pathToFollow,
                        () -> getState().Pose,
                        () -> getState().Speeds,
                        (speeds, feedforwards) ->
                            setControl(
                                m_pathApplyRobotSpeeds
                                    .withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                                    .withWheelForceFeedforwardsX(
                                        feedforwards.robotRelativeForcesXNewtons())
                                    .withWheelForceFeedforwardsY(
                                        feedforwards.robotRelativeForcesYNewtons())),
                        new PPHolonomicDriveController(
                            new PIDConstants(
                                SwerveConstants.kPathTranslationP,
                                SwerveConstants.kPathTranslationI,
                                SwerveConstants.kPathTranslationD),
                            new PIDConstants(
                                SwerveConstants.kRotationP,
                                SwerveConstants.kRotationI,
                                SwerveConstants.kRotationD)),
                        config,
                        shouldFlip,
                        SwerveConstants.kPathPauseThresholdMeters,
                        SwerveConstants.kPathResumeThresholdMeters,
                        this);
                  },
                  java.util.Set.of(this)),
          () -> getState().Pose,
          pose -> {
            if (m_shouldMirrorPath.getAsBoolean()) {
              pose =
                  new Pose2d(
                      pose.getX(),
                      Constants.FieldSpots.kFieldWidth - pose.getY(),
                      pose.getRotation().unaryMinus());
            }
            resetPose(pose);
          },
          shouldFlip,
          true // isHolonomic
          );

      // Register named command for use in PathPlanner autos
      NamedCommands.registerCommand("StopModules", stopModules());
    } catch (IOException | ParseException ex) {
      DriverStation.reportError(
          "Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
    }
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  /**
   * Stops the drivetrain by applying an idle request. Use this to explicitly stop module targets
   * from latching after autonomous paths complete.
   *
   * @return Command that idles the drivetrain.
   */
  public Command stopModules() {
    return runOnce(() -> setControl(m_idle));
  }

  /**
   * Runs the SysId Quasistatic test in the given direction for the routine specified by
   * m_sysIdRoutineToApply.
   *
   * @param direction Direction of the SysId Quasistatic test
   * @return Command to run
   */
  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  /**
   * Runs the SysId Dynamic test in the given direction for the routine specified by
   * m_sysIdRoutineToApply.
   *
   * @param direction Direction of the SysId Dynamic test
   * @return Command to run
   */
  public Command sysIdDynamic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.dynamic(direction);
  }

  /**
   * Creates a command that continuously faces the robot toward a dynamically supplied field point
   * while allowing driver control of translation.
   *
   * @param targetPointSupplier Supplier for the field point to look at (in meters).
   * @param xVelocitySupplier Supplier for forward velocity (m/s).
   * @param yVelocitySupplier Supplier for left velocity (m/s).
   * @param deadband Deadband for translation velocity (m/s).
   * @return Command that faces the target point while driving.
   */
  public Command lookAtPoint(
      Supplier<Translation2d> targetPointSupplier,
      Supplier<Double> xVelocitySupplier,
      Supplier<Double> yVelocitySupplier,
      double deadband) {
    return run(
        () -> {
          Translation2d targetPoint = targetPointSupplier.get();
          m_lookAtPointPub.set(new Pose2d(targetPoint, Rotation2d.kZero));

          Translation2d robotPosition = getState().Pose.getTranslation();
          Translation2d vectorToTarget = targetPoint.minus(robotPosition);
          Rotation2d angleToTarget = vectorToTarget.getAngle();

          // Adjust for operator perspective (red alliance has 180 degree offset)
          if (!Constants.ifOnBlue()) {
            angleToTarget = angleToTarget.rotateBy(Rotation2d.k180deg);
          }

          setControl(
              m_fieldCentricFacingAngle
                  .withDeadband(deadband)
                  .withVelocityX(xVelocitySupplier.get())
                  .withVelocityY(yVelocitySupplier.get())
                  .withTargetDirection(angleToTarget));
        });
  }

  /**
   * Overrides path-following rotation to aim at the SOTF-calculated aim point while the
   * translational path is still followed. Uses ShootingOnTheFly to lead the target based on robot
   * velocity and time-of-flight. Run this alongside a path-following command via .alongWith() or as
   * a named command event marker.
   *
   * @return Command that overrides rotation during path following to aim at the hub.
   */
  public Command aimAtHubDuringPath() {
    PIDController aimPid =
        new PIDController(
            SwerveConstants.kRotationP, SwerveConstants.kRotationI, SwerveConstants.kRotationD);
    aimPid.enableContinuousInput(-Math.PI, Math.PI);

    return Commands.startEnd(
        () ->
            PPHolonomicDriveController.overrideRotationFeedback(
                () -> {
                  Pose2d robotPose = getState().Pose;
                  ChassisSpeeds fieldSpeeds =
                      ChassisSpeeds.fromRobotRelativeSpeeds(
                          getState().Speeds, robotPose.getRotation());
                  ChassisSpeeds fieldAccel =
                      ChassisSpeeds.fromRobotRelativeSpeeds(
                          getAcceleration(), robotPose.getRotation());
                  Translation2d aimPoint =
                      ShootingOnTheFly.calculateAimingPoint(
                          robotPose,
                          fieldSpeeds,
                          fieldAccel,
                          Constants.FieldSpots.getHubPosition(),
                          Constants.ShooterConstants.kSOTFLatencyCompensation,
                          Constants.ShooterConstants.TIME_OF_FLIGHT_MAP);
                  double desiredHeading =
                      aimPoint.minus(robotPose.getTranslation()).getAngle().getRadians();
                  double currentHeading = robotPose.getRotation().getRadians();
                  return aimPid.calculate(currentHeading, desiredHeading);
                }),
        PPHolonomicDriveController::clearRotationFeedbackOverride);
  }

  @Override
  public void periodic() {
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply it regardless
     * of DS state. This allows us to correct the perspective in case the robot code restarts
     * mid-match. Otherwise, only check and apply the operator perspective if the DS is disabled.
     * This ensures driving behavior doesn't change until an explicit disable event occurs during
     * testing.
     */
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }

    m_prevFieldSpeeds = m_currentFieldSpeeds;
    m_currentFieldSpeeds = getState().Speeds;
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - m_lastSimTime;
              m_lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   */
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * <p>Note that the vision measurement standard deviations passed into this method will continue
   * to apply to future measurements until a subsequent call to {@link
   * #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the form
   *     [x, y, theta] transposed, with units in meters and radians.
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters,
      double timestampSeconds,
      Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(
        visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
  }

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds.
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }

  /**
   * Gets the shooter position on the field, accounting for robot pose and shooter offset.
   *
   * @return the shooter position as a Translation2d.
   */
  public Translation2d getShooterPosition() {
    Pose2d robotPose = getState().Pose;
    Translation2d shooterOffset2d =
        new Translation2d(FuelConstants.kShooterOffset.getX(), FuelConstants.kShooterOffset.getY());
    return robotPose.getTranslation().plus(shooterOffset2d.rotateBy(robotPose.getRotation()));
  }

  /**
   * Gets the distance from the shooter to the goal center for lookup table purposes.
   *
   * @return the lookup table distance in meters.
   */
  public double getLookupDistanceToGoal() {
    Translation2d goalPosition = Constants.FieldSpots.getHubPosition();
    // idk why we are shooting far only at comp, hack to adjust distance lookup table
    double realDistance = getState().Pose.getTranslation().getDistance(goalPosition) - 0.610;
    return Math.max(0.0, realDistance);
  }

  /**
   * Gets the aim point for looking at the goal. This projects the shooter-to-goal angle from the
   * robot center to give a point 10m away that the drivetrain can aim at.
   *
   * @return the aim point as a Translation2d.
   */
  public Translation2d getGoalAimPoint() {
    Pose2d robotPose = getState().Pose;
    Translation2d shooterPosition = getShooterPosition();
    Translation2d goalPosition = Constants.FieldSpots.getHubPosition();
    Rotation2d aimAngle = goalPosition.minus(shooterPosition).getAngle();
    return robotPose
        .getTranslation()
        .plus(new Translation2d(aimAngle.getCos(), aimAngle.getSin()).times(10.0));
  }

  public ChassisSpeeds getAcceleration() {
    ChassisSpeeds currentSpeeds = getState().Speeds;

    return currentSpeeds.minus(m_prevFieldSpeeds).div(0.02);
  }

  // ── GoToPose command factories ──────────────────────────────────────

  /**
   * Creates a command to drive to a pose with default config and alliance flipping.
   *
   * @param goal Blue-origin target pose.
   * @return Command that drives to the pose.
   */
  public Command goToPose(Pose2d goal) {
    return GoToPoseFactory.goTo(this, goal, GoToPoseCommand::isRedAlliance).withName("GoToPose");
  }

  /**
   * Creates a command to drive to a pose with optional mirroring.
   *
   * @param goal Blue-origin target pose.
   * @param mirror If true, mirror across centerline before alliance flip.
   * @return Command that drives to the pose.
   */
  public Command goToPose(Pose2d goal, boolean mirror) {
    return GoToPoseFactory.goTo(this, goal, GoToPoseCommand::isRedAlliance, mirror)
        .withName("GoToPose");
  }

  /**
   * Creates a GoToPose command with a custom config.
   *
   * @param config Custom motion config.
   * @param goal Blue-origin target pose.
   * @param mirror If true, mirror across centerline before alliance flip.
   * @return Command that drives to the pose.
   */
  public Command goToPose(GoToPoseCommand.Config config, Pose2d goal, boolean mirror) {
    return GoToPoseFactory.custom(this, config, () -> goal, GoToPoseCommand::isRedAlliance, mirror)
        .withName("GoToPose");
  }

  /**
   * Creates a fast transit command to a pose with alliance flipping.
   *
   * @param goal Blue-origin target pose.
   * @return Command that drives quickly to the pose with loose tolerances.
   */
  public Command fastTransitTo(Pose2d goal) {
    return GoToPoseFactory.fastTransit(this, goal, GoToPoseCommand::isRedAlliance)
        .withName("FastTransit");
  }

  /**
   * Creates a precise placement command to a pose with alliance flipping.
   *
   * @param goal Blue-origin target pose.
   * @return Command that drives slowly to the pose with tight tolerances.
   */
  public Command precisePlacementTo(Pose2d goal) {
    return GoToPoseFactory.precisePlacement(this, goal, GoToPoseCommand::isRedAlliance)
        .withName("PrecisePlacement");
  }

  /**
   * Creates a fast transit command to a pose relative to the current robot pose. The offset is
   * applied in robot-relative coordinates (forward/left), then converted to field coordinates.
   *
   * @param forwardMeters Distance forward (positive = front of robot).
   * @param leftMeters Distance left (positive = left of robot, negative = right).
   * @return Command that drives to the relative pose.
   */
  public Command fastTransitRelative(double forwardMeters, double leftMeters) {
    return Commands.defer(
            () -> {
              Pose2d currentPose = getState().Pose;
              // Robot-relative offset: forward = +X, left = +Y in robot frame
              Translation2d robotRelativeOffset = new Translation2d(forwardMeters, leftMeters);
              // Rotate offset by robot heading to get field-relative offset
              Translation2d fieldRelativeOffset =
                  robotRelativeOffset.rotateBy(currentPose.getRotation());
              // Calculate goal pose (keep same heading)
              Pose2d goalPose =
                  new Pose2d(
                      currentPose.getTranslation().plus(fieldRelativeOffset),
                      currentPose.getRotation());
              // Use fastTransit without alliance flipping since this is relative movement
              return GoToPoseFactory.fastTransit(this, goalPose);
            },
            java.util.Set.of(this))
        .withName("FastTransitRelative");
  }

  // ── Simulation testing ───────────────────────────────────────────

  private final java.util.Random m_simRandom = new java.util.Random();

  /**
   * Injects a random 0.5–1.5m offset into the resilient path follower for 2 seconds, making it
   * think the robot is far off the path. This triggers the pause/recovery behavior without fighting
   * the sim physics. Only useful in simulation.
   *
   * @return Command that injects then clears a sim offset.
   */
  public Command simDisturbRobot() {
    return Commands.sequence(
            Commands.runOnce(
                () -> {
                  double distance = 0.5 + m_simRandom.nextDouble() * 1.0;
                  Rotation2d direction = new Rotation2d(m_simRandom.nextDouble() * 2.0 * Math.PI);
                  ResilientFollowPathCommand.injectSimOffset(
                      new Translation2d(distance, direction));
                }),
            Commands.waitSeconds(2.0),
            Commands.runOnce(ResilientFollowPathCommand::clearSimOffset))
        .ignoringDisable(true)
        .withName("SimDisturbRobot");
  }
}
